debugging jupyter fix

diff --git a/.github/workflows/axe.yml b/.github/workflows/axe.yml
--- a/.github/workflows/axe.yml
+++ b/.github/workflows/axe.yml
@@ -44,7 +44,9 @@ jobs:
       - name: Install and Build 🔧
         run: |
           sudo apt-get update && sudo apt-get install -y imagemagick
-          pip3 install --upgrade jupyter
+          pip3 install --upgrade jupyter nbconvert
+          which jupyter || echo "Jupyter not found in PATH"
+          jupyter --version || echo "Jupyter command failed"
           export JEKYLL_ENV=production
           bundle exec jekyll build
       - name: Purge unused CSS 🧹
